##-# orders
CREATE TABLE IF NOT EXISTS orders (
  `order_id` INT UNSIGNED NOT NULL,
  `order_item_id` int(11) NOT NULL,
  `tree_user_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `is_autoship` bool DEFAULT 0,
  `order_date` datetime DEFAULT NULL,
  `currency_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `total` decimal(19,4) DEFAULT '0.0000',
  `sub_total` decimal(19,4) DEFAULT '0.0000',
  `tax_total` decimal(19,4) DEFAULT '0.0000',
  `shipping_total` decimal(19,4) DEFAULT '0.0000',
  `bv_total` decimal(19,4) DEFAULT '0.0000',
  `cv_total` decimal(19,4) DEFAULT '0.0000',
  `discount_total` decimal(19,4) DEFAULT '0.0000',
  `discount_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `timezone` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `shipped_date` datetime DEFAULT NULL,
  `order_shipping_city` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `order_shipping_state` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `order_shipping_zip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `order_shipping_country` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `order_shipping_county` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `order_tracking_number` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  `client_order_id` int(11) DEFAULT NULL,
  `client_user_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `product_id` int(11) DEFAULT NULL,
  `product_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `product_description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `price_each` decimal(19,4) DEFAULT '0.0000',
  `price_total` decimal(19,4) DEFAULT '0.0000',
  `weight_each` decimal(19,4) DEFAULT '0.0000',
  `weight_total` decimal(19,4) DEFAULT '0.0000',
  `tax` decimal(19,4) DEFAULT '0.0000',
  `bv` decimal(19,4) DEFAULT '0.0000',
  `bv_each` decimal(19,4) DEFAULT '0.0000',
  `cv_each` decimal(19,4) DEFAULT '0.0000',
  `cv` decimal(19,4) DEFAULT '0.0000',
  `parent_product_id` int(11) DEFAULT NULL,
  `item_tracking_number` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `item_shipping_city` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `item_shipping_state` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `item_shipping_zip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `item_shipping_county` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `item_shipping_country` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (order_id, order_item_id)
) ENGINE=Innodb;
#-##

REPLACE INTO `orders`
SELECT
  o.id,
  i.order_item_id,
  o.tree_user_id,
  t.description AS `type`,
  s.description AS `status`,
  IF(o.`autoship_template_id` > 0, 1, 0),
  o.`order_date`,
  o.`currency_code`,
  o.`total`,
  o.`sub_total`,
  o.`tax_total`,
  o.`shipping_total`,
  o.`bv_total`,
  o.`cv_total`,
  o.`discount_total`,
  o.`discount_code`,
  o.`timezone`,
  o.`shipped_date`,
  o.`shipping_city`,
  o.`shipping_state`,
  o.`shipping_zip`,
  o.`shipping_country`,
  o.`shipping_county`,
  o.`tracking_number`,
  o.`created_date`,
  o.`modified_date`,
  o.`client_order_id`,
  o.`client_user_id`,
  i.`product_id`,
  i.`product_code`,
  i.`product_description`,
  i.`quantity`,
  i.`price_each`,
  i.`price_total`,
  i.`weight_each`,
  i.`weight_total`,
  i.`tax`,
  i.`bv`,
  i.`bv_each`,
  i.`cv_each`,
  i.`cv`,
  i.`parent_product_id`,
  i.`tracking_number`,
  i.`shipping_city`,
  i.`shipping_state`,
  i.`shipping_zip`,
  i.`shipping_county`,
  i.`shipping_country`
FROM `pyr-idlife-prod`.tree_orders o
INNER JOIN `pyr-idlife-prod`.tree_order_items i ON o.id = i.order_id
INNER JOIN `pyr-idlife-prod`.tree_order_types t ON o.order_type_id = t.id
INNER JOIN `pyr-idlife-prod`.tree_order_statuses s ON o.order_status_id = s.id;
#-##
